#!/bin/sh
# gen-static-ffi.sh
# Generate a C source file that registers exported symbols from static
# libraries (.a files) via Sforeign_symbol(), enabling FFI access to
# statically linked libraries.
#
# Usage: gen-static-ffi.sh lib1.a [lib2.a ...] > static_ffi.c

if [ $# -eq 0 ]; then
    echo "Usage: $0 lib1.a [lib2.a ...] > static_ffi.c" >&2
    exit 1
fi

# Verify all input files exist
for lib in "$@"; do
    if [ ! -f "$lib" ]; then
        echo "Error: $lib not found" >&2
        exit 1
    fi
done

# Collect all exported text symbols from the .a files
# nm --defined-only -g shows only globally defined symbols
# Filter for type T (text/code) symbols
syms=$(nm --defined-only -g "$@" 2>/dev/null | awk '$2 == "T" { print $3 }' | sort -u)

if [ -z "$syms" ]; then
    echo "Warning: no exported text symbols found in: $*" >&2
fi

cat <<'HEADER'
/* Generated by gen-static-ffi.sh -- do not edit */
#include "scheme.h"

HEADER

# Generate extern declarations
for sym in $syms; do
    # Skip compiler/runtime internal symbols (leading underscore on some platforms)
    case "$sym" in
        _*) continue ;;
    esac
    printf 'extern void %s();\n' "$sym"
done

cat <<'MIDDLE'

void static_ffi_init(void) {
MIDDLE

# Generate Sforeign_symbol registrations
for sym in $syms; do
    case "$sym" in
        _*) continue ;;
    esac
    printf '    Sforeign_symbol("%s", (void *)%s);\n' "$sym" "$sym"
done

cat <<'FOOTER'
}
FOOTER
